# See https://github.com/travis-ci/travis-ci/issues/7587

matrix:
  include:
    - {osx_image: xcode10, os: osx}
    - {osx_image: xcode9.4, os: osx}
    - {osx_image: xcode9.3, os: osx}
    - {osx_image: xcode9.2, os: osx}
    - {osx_image: xcode9.1, os: osx}
    - {osx_image: xcode9, os: osx}
    - {osx_image: xcode8.3, os: osx}
    - {osx_image: xcode8, os: osx}
    - {osx_image: xcode7.3, os: osx}
    - {osx_image: xcode6.4, os: osx}

before_install:
  # prevent garage from exiting on config
  - cp garage/config_personal_template.py garage/config_personal.py
  - echo "${MJKEY}" > mjkey.txt
  # clear pre-installed homebrew packages
  # - brew list -1 | xargs brew uninstall
  # Uninstall oclint which conflicts with GCC
  # See https://github.com/travis-ci/travis-ci/issues/8826
  - brew cask uninstall oclint
  # Install updated XCode CLT
  # See https://github.com/travis-ci/travis-ci/issues/9640
  - if [ "${TRAVIS_OSX_IMAGE}" = "xcode9.4" ]; then ( sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4" )& fi
  - if [ "${TRAVIS_OSX_IMAGE}" = "xcode9.3" ]; then ( sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3" )& fi
  # Start Xvfb
  # See https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x16 +iglx; echo ok )& fi
  - export DISPLAY=:99

install:
  - bash scripts/setup_osx.sh --mjkey mjkey.txt --modify-bashrc

before_script:
  - source ${HOME}/.bash_profile
  - . ${HOME}/miniconda2/etc/profile.d/conda.sh
  - conda activate garage
  - export DISABLE_MUJOCO_RENDERING=1

script:
  - nose2 -c setup.cfg -E 'not huge'

notifications:
  email: false
